### ISSUE TITLE
Fusion container class not rendered

### ISSUE THREAD

**Issue by simonhir** [bwaidelich/Wwwision.Form.MultiColumnSection#4]
Hi @bwaidelich,

first of all thanks for the handy plugin.

I noticed a small bug under fusion where the `row`-class of the outer `div`-element ist not rendered.
The problem is `class.@if.hasCustomClass` within https://github.com/neos/form-fusionrenderer/blob/master/Resources/Private/Fusion/Core/AbstractSection.fusion#L6.

The solution i have implemented is adding the following default property to the Configuration/Settings.yaml:
```yaml
Neos:  
  Form:
    presets:
      default:
        formElementTypes:
          'Wwwision.Form.MultiColumnSection:TwoColumns':
            properties:
              elementClassAttribute: 'row'
```

In my opinion thats the better way than setting the if-statement to `true` inside the fusion-element.

If you like i would open a MR for that.

Many greetings
Simon
